### ISSUE TITLE
Fix map view on web, map displays "for development purposes only" watermarks

### ISSUE THREAD

**Issue by Ethan-Johnson-NZ** [koha-app/koha#28]

**Comment by Ethan-Johnson-NZ** [comment]
This issue is related to Googles changes to the billing system.
See, https://stackoverflow.com/questions/50977913/google-maps-shows-for-development-purposes-only

> Google Maps is no longer free. You have to associate a credit card so that you can get billed if your site has requests that exceed the $200 credit they give you monthly for free. That is why you get the watermarked maps.

**Comment by shaninenueva** [comment]
Issue not relevant to app functions but rather google account, therefore not necessary
